// publications.js

import pdf0 from '../../assets/pdf/Darshan.pdf'
import pdf1 from '../../assets/pdf/a4.pdf'
import pdf2 from '../../assets/pdf/a5.pdf'
import pdf3 from '../../assets/pdf/a7.pdf'
import pdf4 from '../../assets/pdf/a10.pdf'
import pdf5 from '../../assets/pdf/a11.pdf'
import pdf6 from '../../assets/pdf/a6.pdf'
import pdf7 from '../../assets/pdf/a12.pdf'
import pdf8 from '../../assets/pdf/a8.pdf'
export const PublicationApi = [
   {
    id: 1,
    name: "International Journal of Plant & Soil Science",
    title: "Incorporation of Integrated Nutrient Management on Physio-chemical Characteristics on Tomato  (Solanum lycopersicum L.)",
    volume: "37(9)",
    date: "26 August, 2025",
    pdf: pdf0,
  },
    {
    id: 2,
    name: "Archives of Current Research International",
    title: "Remote Sensing Applications in Fruit Crops: A Review",
    volume: "25(8)",
    date: "21 August, 2025",
    pdf: "https://api.ecrop.co/assets/precisiongrow/Vairagar2582025ACRI142175.pdf",
  },
   {
    id: 3,
    name: "Sunshine Agriculture e-Newsletter",
    title: "Digital Soil Mapping and Precision Farming",
    volume: "5(8)",
    date: "19 August, 2025",
    pdf: "https://api.ecrop.co/assets/precisiongrow/Sunshine-2025-5-8-28-31.pdf",
  },
  {
    id: 4,
    name: "Agrospheres:e- Newsletter",
    title: "Potential of Exotic Vegetables in Indian Markets",
    volume: "6(8)",
    date: "16 August, 2025",
    pdf: "https://api.ecrop.co/assets/precisiongrow/Agrospheres-2025-6-8-33-36.pdf",
  },
  {
    id: 5,
    name: "Agriculture Bulletin",
    title: "Drone and Remote Sensing Applications in Crop Monitoring",
    volume: "1(8)",
    date: "August, 2025",
    pdf: pdf1,
  },
   {
    id: 6,
    name: "Agriculture Bulletin",
    title: "Post-Harvest Loss Assessment in Keys Crops",
    volume: "1(8)",
    date: "August, 2025",
    pdf: pdf2,
  },
   {
    id: 7,
    name: "Agriculture Bulletin",
    title: "Role of Precision Horticulture in Enhancing Productivity and Resource Use Efficiency",
    volume: "1(8)",
    date: "August, 2025",
    pdf: pdf3,
  },
   {
    id: 8,
    name: "Agriculture Bulletin",
    title: "ICT-Based Solutions for Farmers: Mobile Apps and Digital Platforms",
    volume: "1(8)",
    date: "August, 2025",
    pdf: pdf4,
  },
   {
    id: 9,
    name: "Agriculture Bulletin",
    title: "Integrated Nutrient Management for Higher Productivity and Soil Health",
    volume: "1(8)",
    date: "August, 2025",
    pdf: pdf5,
  },
   {
    id: 10,
    name: "Agriculture Bulletin",
    title: "Evaluating Farmer Satisfaction with e-Mandi Platforms",
    volume: "1(8)",
    date: "August, 2025",
    pdf: pdf6,
  },
   {
    id: 11,
    name: "Agriculture Bulletin",
    title: "Precision Planting Techniques for Higher Yields",
    volume: "1(8)",
    date: "August, 2025",
    pdf: pdf7,
  },
   {
    id: 12,
    name: "Agriculture Bulletin",
    title: "Precision Farming : Tools and Techniques",
    volume: "1(8)",
    date: "August, 2025",
    pdf: pdf8,
  },
{
    id: 13,
    name: "Agriculture Bulletin",
    title: "Innovative Bussiness Models Emerging from Agri-Incubators ",
    volume: "1(8)",
    date: "August, 2025",
    pdf: 'https://api.ecrop.co/assets/precisiongrow/August-06.pdf',
  },
  {
    id: 14,
    name: "Current Agriculture Trends",
    title: "Smart Farming: How IoT and AI are Revolutionizing Crop Management ",
    volume: "4(7)",
    date: "22 July, 2025",
    pdf: 'https://api.ecrop.co/assets/precisiongrow/CAT-2025-4-7-35-37.pdf',
  },
    {
    id: 15,
    name: "Current Agriculture Trends",
    title: "Regenerating Agricultural Soils through Organic Carbon",
    volume: "4(7)",
    date: "21 July, 2025",
    pdf: 'https://api.ecrop.co/assets/precisiongrow/CAT-2025-4-7-83-86.pdf',
  },

    {
    id: 16,
    name: "Agrospheres:e- Newsletter",
    title: "The Role of Biofertilizers and Biopesticides in Sustainable Agriculture",
    volume: "6(7)",
    date: "18 July 2025",
    pdf: 'https://api.ecrop.co/assets/precisiongrow/Agrospheres-2025-6-7-96-100.pdf',   
  },
  {
    id: 17,
    name: "Agrospheres:e- Newsletter",
    title: "How Cover Cropping is Transforming Modern Farming",
    volume: "6(7)",
    date: "12 July 2025",
    pdf: 'https://api.ecrop.co/assets/precisiongrow/Agrospheres-2025-6-7-10-13.pdf',   
  },
    {
    id: 18,
    name: "Agrospheres:e- Newsletter",
    title: "Soil Health and Carbon Sequestration Techniques: Pathways to Sustainable Agriculture",
    volume: "6(7)",
    date: "12 July 2025",
    pdf: 'https://api.ecrop.co/assets/precisiongrow/Agrospheres-2025-6-7-79-83.pdf',   
  },
   {
    id: 19,
    name: "Agrospheres:e- Newsletter",
    title: "Carbon Farming: Agriculture's Contribution to Halting Climate Change",
    volume: "6(7)",
    date: "11 July 2025",
    pdf: 'https://api.ecrop.co/assets/precisiongrow/Agrospheres-2025-6-7-6-9.pdf',
  },
    {
    id: 20,
    name: "Current Agriculture Trends",
    title: "Drone-Enabled Herbicide Automation with AI-Weed Detection: Transforming Precision Weed Management",
    volume: "4(7)",
    date: "10 July, 2025",
    pdf: 'https://api.ecrop.co/assets/precisiongrow/CAT-2025-4-7.pdf',
  },
   {
    id: 21,
    name: "Agrospheres:e- Newsletter",
    title: "Strategies for Increasing Maize Yields in Variable Climates",
    volume: "6(7)",
    date: "4 July, 2025",
    pdf: 'https://api.ecrop.co/assets/precisiongrow/Agrospheres-2025-6-7-30-32.pdf',
  },
  {
    id: 22,
    name: "Agriculture Bulletin",
    title: "KVK's Promoting Integrated Farming Systems(IFS)",
    volume: "1(7)",
    date: "July, 2025",
    pdf: 'https://api.ecrop.co/assets/precisiongrow/Agriculture-Bulletin-12.pdf',
  },
  {
    id: 23,
    name: "Agriculture Bulletin",
    title: "Impact of Carbon Markets on Farm Incomes",
    volume: "1(7)",
    date: "July, 2025",
    pdf: 'https://api.ecrop.co/assets/precisiongrow/Agriculture-Bulletin-4.pdf',
  },
  {
    id: 24,
    name: "Agriculture Bulletin",
    title: "Crop Price Forecast & Market Linkages: Enhancing Farmer Income and Market Efficiency",
    volume: "1(7)",
    date: "July, 2025",
    pdf: 'https://api.ecrop.co/assets/precisiongrow/Agriculture-Bulletin-11.pdf',
  },
    {
    id: 25,
    name: "Agriculture Bulletin",
    title: "KVK's Contribution to Doubling Farmers' Income",
    volume: "1(7)",
    date: "July, 2025",
    pdf: 'https://api.ecrop.co/assets/precisiongrow/Agriculture-Bulletin-9.pdf',
  },
     {
    id: 26,
    name: "Krishi Pravahika",
    title: "Promoting carbon farming and climate credit through agricultural extension",
    volume: "5(7)",
    date: "July, 2025",
    pdf: pdf1,
  },
    {
    id: 27,
    name: "Agrospheres:e- Newsletter",
    title: "Developing Agribusiness Partnerships and Networks",
    volume: "6(6)",
    date: "16 June, 2025",
    pdf: 'https://api.ecrop.co/assets/precisiongrow/Agrospheres-2025-6-6-32-35.pdf',
  },
  {
    id: 28,
    name: "Agrospheres:e- Newsletter",
    title: "Sowing Equality: Gender Inclusiveness in Sustainable Agriculture",
    volume: "6(6)",
    date: "13 June, 2025",
    pdf: 'https://api.ecrop.co/assets/precisiongrow/Agrospheres-2025-6-6-48-52.pdf',
  },

 
  {
    id: 29,
    name: "Agriculture Bulletin",
    title: "Novel Ways to Use Water for 'Per Drop More Crop'",
    volume: "1(6)",
    date: "June, 2025",
    pdf: 'https://api.ecrop.co/assets/precisiongrow/f-1-6.pdf',
  },
  {
    id: 30,
    name: "Agriculture Bulletin",
    title: "Mobile Apps for Real Time Agronomic Decision Making",
    volume: "1(6)",
    date: "June, 2025",
    pdf: 'https://api.ecrop.co/assets/precisiongrow/a-1-6-5.pdf',
  },
 
  {
    id: 31,
   name: "Agrospheres:e- Newsletter",
    title: "Role of Drones in Precision Agriculture",
    volume: "6(5)",
    date: "16 May, 2025",
    pdf: 'https://api.ecrop.co/assets/precisiongrow/Agrospheres-2025-6-5-31-33.pdf',
  },
   {
    id: 32,
    name: "Agrospheres:e- Newsletter",
    title: "Impact of Global Trade Policies on Agriculture",
    volume: "6(5)",
    date: "14 May, 2025",
    pdf: 'https://api.ecrop.co/assets/precisiongrow/Agrospheres-2025-6-5-25-27.pdf',
  },
    {
    id: 33,
    name: "Agrospheres:e- Newsletter",
    title: "Role of Remote Sensing and GIS in Horticultural Crop Management",
    volume: "6(5)",
    date: "10 May, 2025",
    pdf: 'https://api.ecrop.co/assets/precisiongrow/Agrospheres-2025-6-5-61-64.pdf',
  },
   {
    id: 34,
    name: "Krishi Pravahika",
    title: "Increasing use of robotics and automation in agriculture (Hindi)",
    volume: "5(8)",
    date: "May, 2025",
    pdf: "https://api.ecrop.co/assets/precisiongrow/Krishipravahika-2025-5-8-18-20.pdf",
  },
  {
    id: 35,
    name: "Agri Magazine",
    title: "Future farming with the integration of artificial ecological policies and artificial intelligence.(Hindi)",
    volume: "2(5)",
    date: "May, 2025",
    pdf: 'https://api.ecrop.co/assets/precisiongrow/H-AGM-02-05-04-06.pdf',
  },
  {
    id: 36,
    name: "Agri Magazine",
    title: "Carbon Credits for Farmers Challenges and Opportunities",
    volume: "2(5)",
    date: "May, 2025",
    pdf: 'https://api.ecrop.co/assets/precisiongrow/E-AGM-02-05-233-236.pdf',
  },
  {
    id: 37,
    name: "Agri Articles",
    title: "Precision Agriculture: Increasing Yields through  Data-Supported Decisions",
    volume: "5(2)",
    date: "Mar/Apr, 2025",
    pdf: 'https://api.ecrop.co/assets/precisiongrow/E-05-02-691-693.pdf',
  }
  
    


  

];
